language: java
jdk:
  - oraclejdk9

os:
  - linux
  - osx

before_install:
  - openssl aes-256-cbc -K $encrypted_f142d2b324c4_key -iv $encrypted_f142d2b324c4_iv -in env.json.enc -out env.json -d

script:
  - "./gradlew clean test"
